### ISSUE TITLE
Sample usage 

### ISSUE THREAD

**Issue by ditafaith** [ericlindsey/varres_gmtsar#1]
Hi,
Are there examples of using it with GMTSAR results?

**Comment by ericlindsey** [comment]
Hi, there are no examples, sorry. This code is 8 years old and I have not maintained it or used it myself since then. I believe the main thing I changed from the original varres code written by Piyush was to add "grd_io.py" and modify the "reader.py" class so that it reads GMTSAR .grd files instead of ROI_PAC files. So, that means you should just try running "decompose.py" or "decomposewithmap.py" on the command line and then follow the usage instructions there. Good luck!
